print ("Hello! I have a story for you!")
print ("*You say* Oh! I am listining!")
print ("Ok! Here gose Nothing!")
print ("Once upon a time...")
print ("There were two girls,")
print ("there names were Tokoyo,")
print ("and Milla,")
print ("Tokoyo was eleven and Milla was ten")
print ("*You say* Oooooh!! They have cool names!")
print ("-_-")
print ("*You say* Oops... sorry..")
print ("Just let me continue.")
print ("*You say* Okie doki!")
print ("Tokoyo said 'My! I am so hungry! Arn't you, Milla?'")
print ("'Why yes, Tokoyo! I also am hungry!' said Milla")
print ("'How about we have a picnic?' said Tokoyo")
print ("'Why, yes! That sounds splended Tokoyo!' said Milla")
print ("'I will get the food!' said Tokoyo 'I will get the blanket!' said Milla")
print ("They got the things they needed, and met eachother at the spot they planed,")
print ("They met in the middle of the wood and set up.")
print ("'Tokoyo?' asked Milla 'Yes?' replied Tokoyo")
print ("'Are you sure it is safe out here?' Milla asked Tokoyo")
print ("'I am pretty sure.' anwsered Tokoyo")
print ("'Well... I am not!' said Milla,")
print ("Milla was very afraid of lots of things,")
print ("even at the age of ten.")
print ("'Fine. I guess we can move out of the forest a bit'")
