print ("Hello! I have a story for you!")
print ("*You say* Oh! I am listining!")
print ("Ok! Here gose Nothing!")
print ("Once upon a time...")
print ("There were two girls,")
print ("there names were Tokoyo,")
print ("and Milla,")
print ("Tokoyo was eleven and Milla was ten")
print ("*You say* Oooooh!! They have cool names!")
print ("-_-")
print ("*You say* Oops... sorry..")
print ("Just let me continue.")
print ("*You say* Okie doki!")
print ("Tokoyo said 'My! I am so hungry! Arn't you, Milla?'")
print ("'Why yes, Tokoyo! I also am hungry!' said Milla")
print ("'How about we have a picnic?' said Tokoyo")
print ("'Why, yes! That sounds splended Tokoyo!' said Milla")
